image: cypress/base:12

stages:
  - test
  - update

variables:
  npm_config_cache: '$CI_PROJECT_DIR/.npm'
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/*
    - cache/Cypress
    - node_modules
    - build

install_dependencies_daily:
  image: cypress/browsers:node12.14.1-chrome85-ff81
  stage: test
  script:
    - npm install
  rules:
    - if: '$SCHEDULE_TYPE == "daily_tests"'
  tags:
    - docker1

run_cypress_tests:
  stage: test
  before_script:
    - npm ci
  script:
    - npx cypress run --record
  rules:
    - if: '$SCHEDULE_TYPE == "daily_tests"'
  variables:
    SCHEDULE_TYPE: 'daily_tests'
  tags:
    - docker1

weekly_update_and_tests:
  stage: update
  script:
    - npm update
    - npx cypress run
    - git config --global user.email "update@nevercodealone.de"
    - git config --global user.name "NCA Updater"
    - GIT_REPO_URL=$(git remote get-url origin)
    - GIT_REPO_AUTH_URL=$(echo $GIT_REPO_URL | sed "s#://gitlab-ci-token:[^@]*@#://${username}:${autoupdater}@#")
    - git remote set-url origin $GIT_REPO_AUTH_URL
    - git add package-lock.json
    - git commit -m "Automatically update package-lock.json"
    - git checkout main
    - git pull --rebase
    - git push -f origin main
  cache: {}
  rules:
    - if: '$SCHEDULE_TYPE == "weekly_updates"'
  tags:
    - docker1

