image: cypress/base:12

stages:
  - test
  - update

variables:
  npm_config_cache: '$CI_PROJECT_DIR/.npm'
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/*
    - cache/Cypress
    - node_modules

install_dependencies_daily:
  image: cypress/browsers:node12.14.1-chrome85-ff81
  stage: test
  script:
    - npm install
  rules:
    - if: '$SCHEDULE_TYPE == "daily_tests"'
  tags:
    - docker1

run_cypress_tests:
  stage: test
  script:
    - npx cypress run --record
  rules:
    - if: '$SCHEDULE_TYPE == "daily_tests"'
  variables:
    SCHEDULE_TYPE: "daily_tests"
  tags:
    - docker1

install_dependencies_weekly:
  image: cypress/browsers:node12.14.1-chrome85-ff81
  stage: update
  script:
    - npm update
  rules:
    - if: '$SCHEDULE_TYPE == "weekly_updates"'
  tags:
    - docker1

run_tests_after_update:
  stage: update
  script:
    - npx cypress run
  rules:
    - if: '$SCHEDULE_TYPE == "weekly_updates"'
      when: on_success
  tags:
    - docker1

commit_and_push_updates:
  stage: update
  script:
    - git config --global user.email "update@nevercodealone.de"
    - git config --global user.name "NCA Updater"
    - GIT_REPO_URL=$(git remote get-url origin)
    - GIT_REPO_AUTH_URL=$(echo $GIT_REPO_URL | sed "s#https://#https://updater:$autoupdater@#")
    - git remote set-url origin $GIT_REPO_AUTH_URL
    - git add package-lock.json
    - git commit -m "Automatically update package-lock.json"
    - git checkout main
    - git push origin main
  rules:
    - if: '$SCHEDULE_TYPE == "weekly_updates"'
      when: on_success
  tags:
    - docker1
